# Generated by Django 5.1.4 on 2024-12-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_book_providers_movie_providers_show_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='tmdb_id',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
