# Generated by Django 5.1.4 on 2024-12-22 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_provider_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='parent_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_providers', to='main.provider'),
        ),
    ]
