# Generated by Django 5.1.4 on 2024-12-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_provider_parent_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='tmdb_id',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='is_complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='show',
            name='seasons',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='show',
            name='tmdb_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='show',
            name='was_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
